# Generated by Django 5.2.4 on 2025-08-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='WatchList',
            new_name='Watchlist',
        ),
    ]
